enterNVL()
enter('CONTROL', 'b')
if not getSwitch('d1_01_control') then
	enter('YOU', 'd')
	speak('CONTROL', "Your name was Phoebe, right? It's nice to meet you. I'm Nika.")
	speak('YOU', "Nice to meet you as well.")
	speak('CONTROL', "I'm so jealous you'll be going off to explore with Jeanne and Amador. You'll take lots of scans for me, right?")
	speak('YOU', "Scans?")
	speak('CONTROL', "I absolutely need to show you my LIDAR rig. I named her Bitsy, but she's actually pretty heavy to get that far underground. She takes a 3D scan of cave interiors, and I can use those to make maps for my game.")
	speak('YOU', "Oh, you're a game developer.")
	speak('CONTROL', "Yep! I used to love climbing when I was a teenager but I kind of fell a lot further than I should and now I mostly climb vicariously through the club, or through videogames and simulations and things like that.")
	speak('CONTROL', "I'll have to show you Spelonky too. It's my capstone project game for my CS degree. It uses generative AI along with LIDAR scans from real caves to generate ultra-realistic environments. It's like you're right there caving for real!")
	speak('YOU', "That sounds really cool. I'd love a demo sometime.")
	speak('CONTROL', "I can totally do that. Let me get my laptop set up real quick...")
	exit('CONTROL')
	wait(.7)
	enter('CONTROL', 'a')
	speak('CONTROL', "And um... Are you a Scorpio?")
	speak('YOU', "I honestly don't know my starsign. Is that... November?")
	speak('CONTROL', "And some of October, too. You just seem like a really resourceful and passionate person, so I figured, Scorpio. My intuition is usually pretty right about things like these.")
	speak('CONTROL', "Er, I'm rambling. I'll leave you be.")
	speak('YOU', "It's really fine. I'm just as bad -- I talk peoples' ears off about frogs and lizards the first chance I get.")
	speak('CONTROL', "Haha, that's so Scorpio.")
	speak('CONTROL', "Okay, here we go. Spelonky's all loaded up. Ready to take a look?")
	speak('YOU', "I'm not great at games, but, sure, let's see.")
	exit('CONTROL')
	wait(.7)
	enter('CONTROL', 'b')
	speak('CONTROL', "Wait, what?")
	speak('YOU', "Is that supposed to happen?")
	speak('CONTROL', "Must be a glitch. Or Bitsy had a bad scan. I swear I'm better at programming than this!")
	speak('YOU', "Probably it's just my bad luck.")
	speak('CONTROL', "Let me reboot it. Or, wait, maybe you'd be better off just seeing it tomorrow once I have the new scans in.")
	exit('YOU')
end
speak('CONTROL', "Stupid Spelonky... How does that even happen? You're a temperamental little program, you know that? I'm going to debug the hell out of you. Just you wait.")
exitNVL()

setSwitch('d1_01_control', true)
play('d1_01_next')
