enterNVL()
enter('YOU', 'b')
speak('YOU', "Phew...")
enter('PAL', 'd')
speak('YOU', "I had no idea what you were asking me to do when we met up this morning, Amador, but this certainly beats paying $10.99 for you to enjoy unlimited waffles or something.")
speak('PAL', "Hey, if I'm going to con you into paying for my breakfast, I'll at least make sure you get something out of it.")
speak('PAL', "So what do you think, Phoebe? How'd you like your first taste of the underground?")
speak('YOU', "I'm just relieved I have another chance at my degree.")
speak('PAL', "Tomorrow we're going to be moving some equipment from the surface down to Big Flat to set up a camp.")
speak('YOU', "A camp? Like to sleep down there?")
speak('PAL', "Jeanne didn't stress it enough, but this place is is BIG. You up for the challenge?")
speak('YOU', "I have no idea if I'm up for it or not. But I have to do it. There's no other choice, so I've got to learn fast and make this my thing.")
speak('PAL', "I... was kind of hoping you'd be more enthusiastic than that.")
speak('YOU', "This is my enthusiastic face. I am absolutely determined. It doesn't matter how I feel because I've got to absolutely commit myself to this. You watch me. I'll be the best caver you've ever seen, if it means getting my PhD.")
speak('PAL', "Haha, okay. I'm convinced.")
exit('PAL')
wait(.3)
enter('PAL', 'e')
speak('PAL', "Just... Take care of yourself, alright?")
speak('YOU', "Thanks. I've been sort of running ragged, recently.")
speak('PAL', "That scar on your face... It's a burn, isn't it?")
speak('YOU', "Is it that noticeable?")
speak('PAL', "Maybe not to everyone, but, like...")
speak('PAL', "I know you used to do that to yourself when we were teenagers. I just want to make sure you're doing okay.")
speak('YOU', "I'll be alright. I'm just stressed at the moment, because, well, my life is falling apart.")
speak('PAL', "A&M has decent therapists if you need 'em. Just know you're not alone out there.")
speak('PAL', "See ya in the cave tomomrrow.")
exit('PAL')
speak('YOU', "Thanks, Amador. Really.")
exitNVL()

fade('black', 2)
fadeOutBGM(2)

setSwitch('d1_06', true)

teleport('Cave03_BigFlat', 'start', 'NORTH', true)
fade('normal', 2)
