enterNVL()
enter('PAL', 'b')
speak('PAL', "Phoebe! Glad you could make it. Feels like I last saw you in the Cretaceous.")
enter ('YOU', 'd')
speak('YOU', "It's really, really good to see you Amador. I'm sorry if I kept you waiting.")
speak('PAL', "Nah I was late too. Don't sweat it.")
speak('YOU', "I was up all last night drafting a grant proposal, and I haven't slept well since I got back from the lagoon trip, and my thesis advisor's going to kill me, because - ")
exit('YOU')
enter('YOU', 'e')
speak('YOU', " - ran so over budget, and the grant didn't come through, so I had to pay out of pocket, and if student debt doesn't kill me, I think Dr. Mehta will, because I came back empty-handed AGAIN, and two days late, and - ")
speak('PAL', "Wait wait wait. Phoebe, slow down. Your brain works about ten times the speed of mine.")
exit('YOU')
enter('YOU', 'd')
speak('YOU', "I'm sorry, I'm sorry. It's just such a relief to see a pleasant face. I swear you're the only friend I've got left.")
speak('YOU', "Or, the only friend I haven't driven off yet.")
speak('PAL', "Hey, you can't drive me off. The only driving you're doing today is driving both of us to IHOP so we can catch some waffles and catch up on life.")
speak('YOU', "I sold my car to pay for the lagoon trip. A&M University didn't even cover my airfare...")
speak('PAL', "Damn, Phoebe.")
speak('PAL', "Just, damn.")
speak('YOU', "Yeah. My life sucks hard.")
speak('PAL', "Maybe today's the day your academic career turns around then. You remember why I wanted to meet up?")
speak('YOU', "So I could treat you to breakfast.")
speak('PAL', "No! I mean that's half the reason. But it was mostly because there are some people I want you to meet. They're my club buddies.")
speak('YOU', "No offense Amador but you keep really weird friends.")
speak('PAL', "Everyone's my friend, and these guys will be your friends too once you hear what they've found. You're gonna get that PhD. These people are your free ride. Or uh, metaphorical ride. Sorry about the car.")
speak('YOU', "I would literally kill someone to just get my doctorate and get out of here already.")
exit('PAL')
enter('PAL', 'e')
speak('PAL', "Then follow me. The HQ is about an hour's walk from campus. It's one of those prefab buildings they've got set up in the fields for agriculture students. This is your big shot, Phoebe, so come on!")

setSwitch('d1_00', true)
setString('date', "");
setString('time', "");
