enterNVL()
enter('LEADER', 'd')
enter('YOU', 'b')
if not getSwitch('d1_01_leader') then
	speak('LEADER', "Hi, Phoebe. Hope I didn't scare you off.")
	speak('YOU', "Not at all. This seems like a great opportunity.")
	speak('LEADER', "It's an opportunity for everyone. Unexplored spaces are special. We're truly privileged to be the first eyes to witness these places only nature has ever known.")
	speak('YOU', "I know what you mean. I want to make new discoveries and do original research but it's just such tough going.")
	speak('LEADER', "You get it.")
	speak('YOU', "Like, my thesis advisor, Dr. Mehta, she's famous in the herpetology world for discovering over fifteen species of skinks that were previously unknown to science.")
	speak('YOU', "There's this one family, Trachelypsis, that even hangs from trees by their tails. And she was the first to describe them! I want to pioneer like that.")
	speak('LEADER', "My hero has a lot of firsts to his name too. Are you familiar with Professor Stejneger? He used to teach here at A&M but he retired a decade ago.")
	speak('YOU', "I don't know him.")
	speak('LEADER', "He explored the Bridge Caverns, and mapped the Sandstone Cave System too. Founded the National Caving Society. His story actually got me into caving.")
	speak('YOU', "Looks like you get to follow in his footsteps, then.")
	speak('LEADER', "I hope so.")
	exit('LEADER')
	enter('LEADER', 'e')
	speak('LEADER', "But, to do that, I need your word of honor, alright? You don't tell a word about this cave to anyone outside this room.")
	speak('YOU', "Okay?")
	exit('LEADER')
	enter('LEADER', 'd')
end
speak('LEADER', "Unexplored spaces are only unexplored once. And it only takes a few loose words to spoil them.")
speak('LEADER', "Just something to keep in mind.")
speak('YOU', "I will, then. Sorry.")
exitNVL()

setSwitch('d1_01_leader', true)
play('d1_01_next')
