enterNVL()
enter('YOU', 'd')
enter('PAL', 'b')
if not getSwitch('d2_02_pal') then
	speak('YOU', "Hey Amador. How goes the scanning?")
	speak('PAL', "I know Nika named this thing Bitsy because it spits out digital bits, but damn that woman sure gave this thing a misnomer. It weights a metric fuckton. I'm getting a workout.")
	speak('YOU', "Ha. Nika seems nice though.")
	speak('PAL', "She's the best. Well, everyone here's great.")
	exit('YOU')
	enter('YOU', 'c')
	speak('YOU', "Jeanne seems to like me, but Tom...")
	speak('PAL', "What's wrong with Tom?")
	speak('YOU', "He doesn't seem thrilled that I'm here.")
	speak('PAL', "Nahhh, don't overthink it. Everyone's excited to have another pair of hands. Bet they want to see some new frogs or whatever just as much as you do.")
	speak('YOU', "Thanks for saying that, but...")
	speak('YOU', "Even Jeanne seems to think that I'm going to call the cops on this whole operation or something. Isn't that a bit paranoid?")
	speak('PAL', "Haha, you're the one being paranoid. The A&M Caving Club is a great crew. We all work fantastic together, and you're one of us already.")
end
speak('PAL', "I know you said you were short on friends, so, try not to doubt your new ones, right? We're like family here.")
speak('YOU', "If you say so...")
exitNVL()

setSwitch('d2_02_pal', true)
play('d2_02_next')