wait(2)

enterNVL()
enter('PAL', 'a')
enter('JERK', 'b')
enter('CONTROL', 'd')
enter('LEADER', 'e')
speak('CONTROL', "You're telling me there was a dead guy down there? Like, a guy? Dead? I can't believe it.")
speak('YOU', "More of a skeleton. I can't get him out of my mind...")
speak('CONTROL', "I wish you'd taken scans. Or at least photos!")
speak('JERK', "There were more pressing things to take care of. Besides, his final resting place is right next to the camp. We'll be back.")
speak('YOU', "I don't know how I feel about going back there when I know there's someone's gravesite right over the next ridge...")
speak('JERK', "Then what do you propose we do?")
speak('PAL', "Kinda got to tell the cops, right?")
speak('LEADER', "Can you imagine how fast we'll be kicked out of there? Not only will the police cordon off the place as a crime scene, they'll probably get in touch with Stejneger and the National Caving Society and turf us out.")
speak('JERK', "Then we never saw him.")
speak('YOU', "What, like, we just pretend?")
exit('JERK')
enter('JERK', 'c')
speak('JERK', "Pretend what? You. Never. Saw. Him.")
speak('JERK', "Not reporting a body would likely be a crime. Failing to notice a body would be negligent, but certainly not something the authorities would hold against you.")
exit('JERK')
enter('JERK', 'b')
speak('LEADER', "I suppose that's right. There's no need to discuss this because it's a moot point. Whatever you saw, Phoebe, you imagined it.")
speak('YOU', "Um...")
speak('LEADER', "You're supposed to say, 'Imagined what?'")
exit('CONTROL')
enter('CONTROL', 'c')
speak('CONTROL', "This sucks. I'm not doing that.")
speak('PAL', "I'm with Nika and Phoebe on this one I think here.")
speak('CONTROL', "Places where people have died are powerful. The energy's just different. I really wish I could capture that energy in Spelonky.")
speak('CONTROL', "Please when you go back to camp, scan the guy with Bitsy. And get good photos. And if you could bring up his personal effects, we could set up a shrine, or - ")
speak('PAL', "Not really where I thought you were going with this, Nika...")
speak('JERK', "There are no personal effects and there is no 'guy'.")
exit('CONTROL')
enter('CONTROL', 'd')
speak('CONTROL', "Aw come on.")
exit('LEADER')
enter('LEADER', 'c')
speak('LEADER', "Look, I don't care what any of you do here, as long as this stays between us. No leaks. Tom, we don't need to gaslight everyone, but Amador, we're keeping the police out of this.")
speak('PAL', "If you say so... I mean, I don't like to call the cops on anyone, friends especially. I'd just hope if I was dead in the ground somewhere, someone would let my mom know at least or something, haha.")
speak('CONTROL', "See, let's do it my way. Bring me his stuff! We'll figure out who this guy was and if he had a family, we'll just discretely let them know.")
speak('CONTROL', "Maybe send them his skull or something.")
speak('LEADER', "No mailing out bodyparts! No outside parties! Light a candle in his skull for all I care, just keep this under wraps until we get to the bottom of the cave.")
speak('LEADER', "Secrecy is paramount. Phoebe, you agree with me, right? You don't want someone to scoop you and find your new species first?")
enter('YOU', 'e')
speak('YOU', "No, but...")
speak('PAL', "Froggus Phoebicus. Has a nice ring to it.")
speak('YOU', "Alright, fine, you're right. It's not like I have a choice. I need this, and it's not going to happen if we bring other people in now.")
speak('YOU', "But I'm one of you all now, okay? I'm in it with you, together.")
speak('JERK', "Agreed.")
speak('PAL', "You always were.")
speak('CONTROL', "This is really exciting now. I thought it was exciting before, but now we have like, a pact.")
speak('LEADER', "A pact is a good word for it. Let's swear on it. Not a word about the corpse until my go ahead.")
speak('LEADER', "I know we wouldn't normally meet tomorrow, but, let's move up the time table. Any objections?")
speak('JERK', "None.")
speak('PAL', "...")
speak('LEADER', "Then I'll see you all tomorrow.")
exit('LEADER')
wait(.6)
exit('YOU')
exit('CONTROL')
exit('JERK')
wait(1)
exit('PAL')
exitNVL()

fade('black', 2)
setSwitch('d2_04', true)
setSwitch('disable_abseiling', true)
teleport('FallCave', 'start')
