wait(9)
radio('CONTROL', "Jeanne, come in. Can you guys -- ", 'bad')
radio('CONTROL', " -- I repeat, can you -- ?", 'bad')
exitRadio()

wait(1.5)

enterNVL()
enter('YOU', 'b')
enter('LEADER', 'd')
speak('YOU', "Is she alright?")
speak('LEADER', "Is the radio having issues?")
enter('JERK', 'e')
speak('JERK', "We're deep enough that depending on the density of the rock above us, it could be blocking radio waves. I wouldn't count on the radio at this depth.")
speak('YOU', "Is that safe?")
enter('PAL', 'a')
speak('PAL', "Nika knows where we are if we don't come up by the end of the day.")
speak('YOU', "But, if something happens, she can't send help right away...")
expr('LEADER', 'serious')
speak('LEADER', "Even if someone does break an arm or something down here, we take care of it ourselves. I'm not willing to risk giving this location away to a rescue team.")
expr('LEADER', '')
speak('YOU', "That, um, seems like you're compromising safety.")
speak('JERK', "What we're doing carries intrinsic risk. We can reduce danger but never eliminate it entirely.")
speak('JERK', "One of the old caving mottos is 'If in doubt, get out.' If you have reservations about what we're doing here, you need to turn around.")
exit('JERK')
speak('YOU', "I didn't say that, I just meant - ")
exit('PAL')
enter('PAL', 'e')
speak('PAL', "Hey Jeanne, how's this spot look for a base camp? Pretty flat, pretty deep.")
speak('LEADER', "Not bad at all.")
speak('LEADER', "Take some scans while Tom and I set up the rest of the equipment.")
exit('PAL')
speak('YOU', "What should I be up to?")
speak('LEADER', "Poke around a bit on this level if you can. There ought to be branches out to lower halls from here, and if we can find one, we have a starting point for the next expedition.")
speak('YOU', "Okay, roger that.")
exitNVL()

setSwitch('d2_01', true)
