enterNVL()
enter('JERK', 'b')
enter('YOU', 'd')
if not getSwitch('d3_04_jerk') then
	speak('JERK', "I'm sorry you have to put up with this, Phoebe. You've been here, what, three days?")
	speak('YOU', "Feels longer than that.")
	speak('JERK', "I know this is a great opportunity for you, but I think Amador oversold it. We should've made very sure what we were getting into before dragging any outsiders into it.")
	expr('JERK', 'grimace')
	speak('JERK', "Jeanne and I aren't amateurs. We've been to the bottom of more than a few very deep mines and caves around here.")
	expr('JERK', 'meh')
	speak('JERK', "And there's nothing special at the bottom of these things. There is no great treasure, and nothing worth dying for.")
	speak('YOU', "I wasn't aware I was risking my life.")
	expr('JERK', '')
	speak('JERK', "Everything carries risk. And maybe I'm being overcautious and we're not in mortal danger down there.")
	speak('JERK', "But this is clearly stressing you out. Don't think I don't notice.")
	speak('YOU', "Oh I'm just stressed from my research. I've been trying and failing for so long that honestly this opportunity feels like a relief.")
	expr('JERK', 'meh')
	speak('JERK', "Then I'm sorry if I misunderstood. I saw that burn on your face, and I may have jumped to conclusions.")
	speak('YOU', "Well... No, my mental health isn't the greatest.")
	speak('JERK', "...Mine wasn't for a long time either. I struggled mightily in undergrad. I felt alone, and insufficient, and unworthy of friendship or support.")
	exit('JERK')
	enter('JERK', 'a', 'meh')
	speak('JERK', "And... I honestly still struggle with relying on others. But you're a good person. You're kind and personable. Don't feel like you're trapped here with us lunatics.")
end
speak('YOU', "Thank you for trusting me. But I'm a lot more persistent than you think, Tom. I know I'm a newbie but I'll help as much as I can. I need this.")
exitNVL()

setSwitch('d3_04_jerk', true)
play('d3_04_next')
