radio('YOU', "Hey! Jeanne, Amador. I found him.")
exitRadio()

wait(1)

enterNVL()
enter('YOU', 'e')
enter('LEADER', 'c', 'serious')
enter('PAL', 'b')
enter('JERK', 'a')
speak('PAL', "Good eyes, Phoebe. I didn't expect that to take this long.")
playBGM('suspense')
speak('YOU', "Because that's not where he was yesterday! He was right next to camp.")
speak('JERK', "Well he didn't get up and walk over there. I'd assume this was a practical joke from Amador but we've been together the whole time.")
speak('LEADER', "It looks close enough to me. I think you're just misremembering.")
expr('YOU', 'dis')
speak('YOU', "I'm not! I swear! He moved!")
speak('JERK', "Amador, help me load his things into the pack.")
speak('PAL', "On it.")
exit('PAL')
wait(1)
enter('PAL', 'd')
speak('PAL', "Hey, the guy's got a A&M student ID.")
expr('LEADER', '')
speak('LEADER', "He's a student?")
speak('PAL', "'Was' a student. His name was Paul, and he was class of '76. Looks like back then they wrote these ID things with a typewriter. Very retro.")
speak('LEADER', "Let me see that.")
expr('LEADER', 'serious')
speak('LEADER', "Paul Stejneger.")
speak('JERK', "He... has the same name as the National Caving Society founder? It's not a common surname. Is there a 'Jr.' or 'Sr.' printed there?")
speak('LEADER', "No. And the photo is...")
speak('JERK', "It matches a young Professor Stejneger, doesn't it? When was the last time anyone saw him?")
speak('LEADER', "He gave a commencement speech just last year. What is his old ID doing down here with this body? It's...")
expr('JERK', 'meh')
speak('JERK', "It's time to go, is what it is. We take this ID and evidence up to Nika, and we contact Stejneger.")
expr('JERK', '')
expr('LEADER', 'dis')
speak('LEADER', "Never! This is OUR cave. We don't need everyone down here, trampling all over, disturbing the unknown, wrecking our chance...")
speak('JERK', "Our pace isn't sustainable. We're getting sloppy, and we're making mistakes. This man died down here. He was recently moved. Until we know the threat, we must be cautious.")
speak('LEADER', "I'm overruling you. We can't stop now.")
expr('JERK', 'dis')
speak('JERK', "We operate via committee. You're not the leader. We vote. Phoebe, you're not formally a member. Amador, what's your vote?")
speak('YOU', "Amador?")
exit('PAL')
enter('PAL', 'b')
speak('PAL', "...")
expr('PAL', 'dis')
speak('PAL', "I want to go deeper.")
speak('JERK', "...")
expr('PAL', '')
speak('PAL', "I don't think I'll be able to sleep until we get to the bottom of this. Figuratively and literally. Haha.")
expr('JERK', '')
speak('JERK', "Listen, Phoebe, Jeanne. Nika can borrow a radio repeater from the College of Engineering. We'll haul it to camp tommorrow, and we'll continue from there.")
speak('JERK', "This place is cut off from the rest of the world. It follows its own rules. We need a link with the outside.")
expr('LEADER', '')
speak('LEADER', "Just for today, let's - ")
speak('PAL', "Actually, I've changed my vote. Tom's right. We come back tomorrow.")
exit('PAL')
expr('YOU', '')
wait(.5)
speak('JERK', "Thank you, Amador.")
exit('JERK')
speak('LEADER', "Sorry, Phoebe, but it looks like this wraps things up for today. Let's turn around.")
exitNVL()

fade('black', 2)
setSwitch('d3_03', true)
setString('time', "11:30 PM")
setString('date', "")
wait(1)
teleport('Clubhouse', 'start', 'NORTH', true)
fade('normal', 2)