enterNVL()
enter('LEADER', 'b', 'serious')
enter('YOU', 'd')
if not getSwitch('d3_04_leader') then
	speak('LEADER', "I'm exhausted. I think arguing with everyone tonight is wearing me out more than the actual caving.")
	speak('YOU', "I didn't think you ever got worn out.")
	expr('LEADER', 'grin')
	speak('LEADER', "Believe it or not, I'm still a human, with human empathy and human limits.")
	expr('LEADER', '')
	speak('LEADER', "I'm worried about Professor Stejneger, but... Nika's going to take care of that for us. While we're underground tomorrow, she'll see if she can get him on the phone.")
	speak('YOU', "You're not worried about tipping him off?")
	speak('LEADER', "I trust Nika not to ruin this for us all. If you don't trust her...")
	speak('YOU', "That's not what I meant! I just...")
	speak('YOU', "I'm sorry. I just stress out easily. And this - ")
	speak('LEADER', " - is hard for all of us. When times are tough, I imagine myself after this whole thing is done.")
	speak('LEADER', "I'll be like a modern Stejneger. I see myself leading expeditions, giving press reports, delivering speeches...")
end
expr('LEADER', 'grin')
speak('LEADER', "Positive ideation. Just imagine yourself fulfilling your goals.")
speak('YOU', "Thanks, I'll try.")
exitNVL()

setSwitch('d3_04_leader', true)
play('d3_04_next')
