enterNVL()
enter('YOU', 'b')
enter('PAL', 'd')
speak('YOU', "Amador! Glad you're here early too.")
speak('PAL', "Hey Phoebe! I was just brewing coffee. I was hoping you'd show this morning.")
speak('YOU', "I couldn't sleep. Kept having nightmares.")
speak('PAL', "That makes two of us.")
speak('YOU', "Really? I remember having to kick you awake on camping trips. When you were younger, you could sleep through a bombing raid.")
speak('PAL', "Haha, yeah I haven't changed much, to be honest. It's just the last few days that things have been rough.")
speak('PAL', "I'm starting to regret dragging you into all this. I waned to do you a favor, yeah, but I also had my own reasons for wanting someone I could trust around to - ")
enter('LEADER', 'e')
exit('PAL')
enter('PAL', 'a')
speak('LEADER', "Good morning all.")
speak('PAL', "Oh, hey Jeanne. Good to see you.")
speak('LEADER', "I guess you guys are as anxious to get back down there as I am.")
speak('LEADER', "I'll go over the plan once Tom and Nika show up, but, we're going to explore the area around the camp today...")
speak('LEADER', "...and bring up the personal effects from the body.")
exitNVL()

setSwitch('d3_01', true)

fade('black', 2)
setString('time', "2:00 PM")
teleport('Cave05_Camp', 'start', 'NORTH', true)
fade('normal', 2)