radio('CONTROL', " - anyone? If anyone can hear me, let me know.")
radio('YOU', "Nika! It's me, Phoebe. We're at the end range of the repeater so we're setting up camp.")
radio('CONTROL', "Nice. The chamber's probably... about 40 meters wide, 100 meter ceiling? About 1300 meters deep?")
radio('YOU', "How'd you know that?")
radio('CONTROL', "Spelonky's churning away. I probably know more about the cave than you do!")
radio('YOU', "Then do you know where Amador is?")
radio('CONTROL', "Still working on that! I need more machines. I'm requesting more server time from the College of Engineering. I'm running out of candles, too.")
radio('YOU', "Candles?")
radio('CONTROL', "For the seance. If I'm going to have the AI contact the dead, there's a spiritual element needed too. Normally physical machines can't reach that plane.")
radio('YOU', "Nika, I swear the cave is real. We're not pranking you, so you don't have to prank us.")
radio('CONTROL', "I'm deadly serious. Death is just one meta level below the plane we operate at. There's a few more 'realer' lives in the meta levels above this ours as well.")
radio('CONTROL', "All I need is enough cycles to turn the generation into a simulation, and then I'll be able to talk to Amador if he really is on the other side.")
radio('YOU', "You think he's dead?")
radio('CONTROL', "Hopefully not, but it doesn't hurt to check. If I can't contact him, I'll start looking for him in the real world, one meta level above. He might've found a way to escape our simulation.")
radio('YOU', "I think the radio signal must be bad. I'm having a hard time following your train of thought. Have you considered taking a nap or something?")
radio('CONTROL', " - good idea. Dreams are sometimes a way to -- across the meta world. I wonder if I can model - ")
exitRadio()
enterNVL()
enter('YOU', 'c')
speak('YOU', "I think I lost her...")
exitNVL()


setSwitch('d4_04_control', true)
play('d4_04_next')