enterNVL()
enter('YOU', 'b')
speak('YOU', "You're... me?")
speak('YOU', "But my scar is gone... And you look... happy?")
enter('OTHER', 'd')
speak('YOU', "What is that? A reptile? Froggus Phoebicus??")
speak('OTHER', "It's more related to the axlotl family, but it's still a huge discovery.") 
expr('OTHER', 'smirk')
speak('OTHER', "There's even an article about it in National Geographic.")
speak('YOU', "And our thesis?")
expr('OTHER', 'flirty')
speak('OTHER', "We're a doctor now. Congratulations.")
speak('YOU', "Then this is the power of positive ideation...")
exitNVL()

setString('date', "Thursday 10/4")
setString('time', "8:00 AM")
teleport('PalMap', 'start')

enterNVL()
enter('YOU', 'c')
speak('YOU', "Ah!")
speak('YOU', "Well it beats dreaming about falling...")
exitNVL()

fade('black', 2)
wait(1)
setString('time', "11:00 AM")
teleport('Clubhouse', 'd4_01')

setSwitch('d4_00', true)