enterNVL()
enter('CONTROL', 'b')
enter('YOU', 'd')
if not getSwitch('d4_01_control') then
	speak('CONTROL', "Hey Phoebe, check it out.")
	expr('CONTROL', 'yay')
	speak('CONTROL', "I've got AI exploration working in Spelonky.")
	speak('YOU', "That's... great, but, is that really what we should be worried about right now?")
	expr('CONTROL', '')
	speak('CONTROL', "I figure it's the best way to find Amador. He clearly went into the cave, right?")
	speak('YOU', "How do you know that?")
	speak('CONTROL', "Because if I could go myself, I wouldn't want to leave that cave. I'd be down there breakfast lunch and dinner. So let's assume Amador's went that way.")
	speak('CONTROL', "I'll run a few hundred million simulations of someone following a random walk down there, and if you average them out, that should take you straight to Amador.")
	speak('YOU', "Your maps of the inside are that good? I thought last night they were all buggy.")
	speak('CONTROL', "Oh they still don't make physical sense, but when I was coding last night, I had this revelation.")
	expr('CONTROL', 'yay')
	speak('CONTROL', "The cave doesn't make physical sense, so the meta-cave doesn't need to either.")
	expr('CONTROL', '')
	speak('YOU', "Nika, have you been up all night?")
	speak('CONTROL', "I got some great tea from my semester abroad. It's infused with woodworms. It'll keep you going for 24, even 48 hours straight. So I lit up some incense in my room and got coding.")
	expr('CONTROL', 'yay')
	speak('CONTROL', "The generative AI is doing its thing now too. I bet I can predict all the chamber layouts straight to the bottom. I could hand you a map right now. Really.")
	expr('CONTROL', '')
	speak('YOU', "That sounds great and all, but, I thought you were supposed to be contacting Professor Stejneger.")
	expr('CONTROL', 'grump')
	speak('CONTROL', "Oh I did that too.")
	expr('CONTROL', '')
	speak('CONTROL', "I got him on the phone.")
	speak('YOU', "He's okay?")
	speak('CONTROL', "I told him we found his dead body while caving and he was pretty nonplussed about it.")
	speak('CONTROL', "Actually he was super positive. I can see why Jeanne likes him. He said we should keep following our dreams and not give up on the cave. He was encouraging. Enthusiastically encouraging.")
	speak('YOU', "I guess that's better than finding out he was dead... But then who is it that we found down there with his ID card?")
	expr('CONTROL', 'yay')
	speak('CONTROL', "Dunno. I'll ask the AI model once I'm done figuring out where Amador went.")
	speak('YOU', "Gotcha...")
else
	enter('CONTROL', 'c', 'yay')
	speak('CONTROL', "Compile! Compile! Compile!")
end
exitNVL()

setSwitch('d4_01_control', true)
play('d4_01_next')
