enterNVL()
enter('JERK', 'b')
enter('YOU', 'd')
if not getSwitch('d4_01_jerk') then
	speak('JERK', "Phoebe, I hate that I have to ask...")
	speak('JERK', "You're sure you can't get in touch with Amador? And don't know where he's going?")
	speak('YOU', "No, it's like I told Jeanne. I've got no idea.")
	speak('JERK', "I just wondered if you didn't trust her enough to tell her.")
	expr('JERK', 'meh')
	speak('JERK', "Given the circumstances, I wouldn't.")
	speak('YOU', "What do you mean?")
	speak('JERK', "...")
	expr('JERK', '')
	speak('JERK', "Amador seemed pretty convinced that we needed to contact the authorities, didn't he?")
	expr('JERK', 'grimace')
	speak('JERK', "And who do we know that would do anything, literally anything, to prevent that?")
	expr('JERK', '')
	speak('YOU', "You can't seriously think that Jeanne would - ")
	expr('JERK', 'grimace')
	speak('JERK', "I didn't name names!")
	expr('JERK', 'meh')
	speak('JERK', "Just... this isn't a good time to go trusting people you don't know.")
end
expr('JERK', 'grimace')
speak('JERK', "...Forget it.")
exitNVL()

setSwitch('d4_01_jerk', true)
play('d4_01_next')
