enterNVL()
enter('LEADER', 'b')
enter('YOU', 'd')
if not getSwitch('d4_01_leader') then
	speak('LEADER', "Hey, YOU, can I get you to promise something?")
	speak('YOU', "Yeah?")
	expr('LEADER', 'serious')
	speak('LEADER', "No matter what happened to Amador, you won't let the university know until after we've found the bottom, right?")
	speak('YOU', "Why? What do you think happened to him? He's got to just be late, right?")
	speak('LEADER', "I think he went solo-exploring last night. He was lying that he wanted to come back up. After we left, he must've double-crossed us and gone freelancing on his own.")
	speak('YOU', "What purpose would that serve?")
	expr('LEADER', '')
	speak('LEADER', "You know him better than I do, right? You tell me. Maybe he's after the glory, or maybe he's just curious. But I can almost guarantee that he's down there, right now.")
	speak('YOU', "Maybe he's trapped... Do you think something could've happened to him down there?")
	expr('LEADER', 'serious')
	speak('LEADER', "We can't rule it out. That's why I want you to promise me, that no matter what happens, you put your goals first.")
	speak('YOU', "This... is probably my last real shot at my doctorate. I understand.")
	expr('LEADER', 'grin')
	speak('LEADER', "I knew you'd get it. Tom doesn't, but he thinks I'm a ghoul. I just want to do what's best for us.")
	expr('LEADER', '')
	speak('LEADER', "Besides, whatever happened to Amador...")
	expr('LEADER', 'serious')
	speak('LEADER', "... It was his fault.")
	speak('YOU', "...")
else
	speak('LEADER', "No matter what happened to Amador, you won't let the university know until after we've found the bottom, right?")
end
exitNVL()

setSwitch('d4_01_leader', true)
play('d4_01_next')
