radio('LEADERD', " -- anyone?", 'bad')
radio('YOU', "Jeanne!? You're alive! Jeanne can you hear me? Are you hurt?")
radio('LEADER', " -- roger. Hi Phoebe. My ankle's swelling but I'll be alright. I'm -- broke 2000 meters, I -- ", 'okay')
radio('YOU', "I thought you were dead. Tom ditched us. Where are you? ")
radio('LEADER', " -- at the bottom. Waiting. We're here, me and -- ", 'okay')
radio('YOU', "The bottom?")
radio('LEADER', " -- truly at peace.", 'bad')
radio('YOU', "Jeanne, are you still there?")
exitRadio()

enterNVL()
enter('YOU', 'c')
speak('YOU', "I need to get to the bottom. I NEED to.")
exitNVL()

setSwitch('d5_03', true)
