enterNVL()
enter('LEADER', 'c')
speak('LEADER', "Wh -")
expr('LEADER', 'serious')
speak('LEADER', "Help, help, help, I'm - ")
speak('LEADER', "I can't die before I reach the bottom! My white whale, my dream, my - ")
exit('LEADER')
speak('LEADER', "Nooo!")
enter('YOU', 'b')
enter('JERK', 'd')
speak('YOU', "Jeanne!")
speak('JERK', "...She slipped down into the shaft.")
expr('JERK', 'meh')
speak('JERK', "That's a lethal fall.")
speak('YOU', "You can't know that! We have to get down there an help her!")
exitNVL()

radio('YOU', "Nika! Nika, come in!")
radio('YOU', "Nika wake up! We need you!")
wait(1)
exitRadio()

enterNVL()
enter('YOU', 'c')
speak('YOU', "Useless radio...")
speak('YOU', "Jeanne, we're coming!")
exit('YOU')
enter('YOU', 'b')
enter('JERK', 'd', 'meh')
speak('YOU', "Tom, help me rappel down there.")
speak('JERK', "I believe this is where our partnership ends, Phoebe.")
speak('YOU', "You can't just abandon your friend!")
expr('JERK', 'grimace')
speak('JERK', "...I wonder if she ever was.")
speak('JERK', "Goodbye, Phoebe.")
exit('JERK')
wait(1)
exit('YOU')
enter('YOU', 'c')
speak('YOU', "Dammit. Damn damn dammit.")
speak('YOU', "Okay, Phoebe. Focus. You're not a total newbie any more. Just picture yourself holding that sweet axlotl. You're fine. You're a doctor. You're famous.")
speak('YOU', "That's me, right down there, once I reach the bottom of this cave. Me and Amador, joking around... Jeanne thanking me for helping her out of this hellhole...")
speak('YOU', "I can do this. I've got to find Jeanne down there, and Amador too, and find the bottom.")
exitNVL()

setSwitch('d5_02', true)
