playBGM('suspense')
enterNVL()
enter('YOU', 'a')
enter('OTHER', 'c')
speak('YOU', "Me... It's you again.")
speak('OTHER', "Me and Amador, too.")
enter('PALD', 'e')
speak('PALD', "Hi, Phoebe. I didn't think I'd see you again so soon, but I'm really glad you're here.")
speak('YOU', "Where are we? Is this the bottom of the cave?")
speak('PALD', "Froggus Phoebicus is looking cute as ever, Phoebe. Almost as cute as you.")
exit('OTHER')
enter('OTHER', 'd', 'flirty')
speak('OTHER', "Hey Amador, you want to grab breakfast? It's on me.")
speak('PALD', "You're really charitable now that you've got that big fancy 'Doctor' in front of your name.")
expr('OTHER', '')
speak('OTHER', "I'm generous because the grant money came through. I could literally pay a grad student to drive us to IHOP and the bursar wouldn't bat an eye at the budget.")
speak('PALD', "Let's hop to it, then!")
exit('PALD')
exit('OTHER')
speak('YOU', "Wait, Amador, come back!")
exitNVL()

setSwitch('d5_00', true)
fade('black', 2)
teleport('Cave09_Camp', 'd5_00', 'NORTH', true)
