wait(1)

enterNVL()
enter('CONTROL', 'a')
enter('LEADER', 'b')
enter('PAL', 'd')
enter('JERK', 'e')
wait(.8)
enter('OTHER2', 'c')
wait(.4)
expr('PAL', 'grin')
speak('PAL', "Phoebe! You finally made it.")
expr('PAL', '')
speak('OTHER2', "Hey everyone. Sorry to keep you waiting. I was up all last night preparing for my thesis defense.")
speak('LEADER', "That's tomorrow?")
expr('OTHER2', 'flirty')
speak('OTHER2', "Yep. Dr. Mehta says I've got it in the bag though.")
expr('OTHER2', 'smirk')
speak('OTHER2', "I mean, the freaking Discovey Channel wants to interview me. The committee would be crazy to fail me now. It'd make A&M look bad.")
expr('OTHER2', '')
speak('JERK', "Congratulations, Phoebe. Your hard work paid off.")
speak('OTHER2', "Thanks, Tom. I really appreciated everyone's support, and yours especially.")
expr('OTHER2', 'flirty')
speak('OTHER2', "It strengthened my research a lot to have your description of minerals in the habitat.")
expr('OTHER2', '')
speak('JERK', "No problem whatsoever. That's what friends are for.")
expr('LEADER', 'grin')
speak('LEADER', "You're coming to the party tomorrow, right?")
expr('LEADER', '')
speak('OTHER2', "Hopefully! I can't wait to meet Professor Stejneger.")
expr('LEADER', 'grin')
speak('LEADER', "And he can't wait to meet me, and all of you. The whole National Caving Society's going to be there.")
expr('LEADER', '')
speak('JERK', "They've certainly taken a shine to you.")
speak('LEADER', "Don't be humble, Tom. They're really happy to have a real scientist like you on board instead of just amateur thrill junkies like me and Amador.")
expr('PAL', 'grin')
speak('PAL', "They'll let me tag along on trips and won't make me pay dues. That's basically all I need to be happy.")
expr('PAL', '')
speak('CONTROL', "You guys need to convince them to take Bitsy along too. Okay, Amador?")
speak('PAL', "I'll see what I can do. Jeanne's gonna need to convince them.")
speak('CONTROL', "Spelonky's going super, but just imagine what I could do if I had data on caves from all over the world.")
expr('CONTROL', 'yay')
speak('CONTROL', "Phoebe, you need to get me your Steam username. I'll send you over a beta key!")
speak('OTHER2', "You're going to sell the game?")
expr('CONTROL', '')
speak('CONTROL', "I'm going indie for now, but a publisher's been in touch. I'm holding out for more revenue share, honestly. These guys just have bad vibes. I can do better.")
speak('JERK', "Smart. Let me know if need another pair of eyes to go over the contract.")
speak('CONTROL', "Thanks Tom. I hate handling the finances.")
speak('OTHER2', "You said you had a demo to show us today, though, Nika?")
speak('CONTROL', "Yep. This should about wrap it up.")

wait(.4)
exitNVL()
wait(.3)
endGame()

play('d6_01')
